server:
  port: 8080

spring:
  #thymeleaf
  thymeleaf:
    mode: HTML
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    #数据库，mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/comment?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    #连接池
    hikari:
      #最大连接处
      maximum-pool-size: 15
      #最小连接处
      minimum-idle: 5
      idle-timeout: 30000
  #邮件发送
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 2624467078@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: ayypscrozgmgdicf
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #use-generated-keys: true
    map-underscore-to-camel-case: true
  mapper-locations:
    classpath: mapper/*.xml
